- name: variables from prompt level
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter the username
    private: false
  - password: PASSWORD
    prompt: please enter the password
    private: true
  tasks:
  - name: print the variables from prompt
    ansible.builtin.debug:
      msg: "username is {{USERNAME}} and password is {{PASSWORD}}"
