- name: variables from commandline
  hosts: localhost
  tasks:
  - name: printing the variables from command line
    ansible.builtin.debug:
      msg: "My name is {{NAME}} and i am learning the {{COURSE}}"