- name: Loops
  hosts: localhost
  tasks:
  - name: printing the multiple names using loops
    ansible.builtin.debug:
      msg: "My pricing team is {{item}}"

    loop:
    - suhail
    - shaik
    - adarsh
    - purushottam
    - subham