- name: installing the multiple packages
  hosts: localhost
  become: yes
  tasks:
  - name:  "installing the {{item}} package"
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    loop:
    - nginx
    - postfix